/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Statistic.xs. Do not edit this file, edit Statistic.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Statistic.xs"
#ifdef __cplusplus
extern "C" {
#endif

#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#define NO_XSLOCKS 
#include "XSUB.h"

#ifdef __cplusplus
} /* extern "C" */
#endif

#include "ppport.h"

#define NDEBUG

#include <vector>
#include <cstddef>
#include <stdexcept>

#include "kth_order_statistic.hpp"
#include "debug.hpp"


/* copied from gfx modules */
class PerlCompare {
    SV* compare_;

    public:
    PerlCompare(SV* compare) : compare_(compare) {}

    int operator()(SV* const x, SV* const y) const {
        dTHX;
        dSP;

        ENTER;
        SAVETMPS;

        PUSHMARK(SP);
        EXTEND(SP, 2);
        PUSHs(x);
        PUSHs(y);
        PUTBACK;

        call_sv(compare_, G_SCALAR);
        SPAGAIN;
        int const ret = POPi;
        PUTBACK;

        FREETMPS;
        LEAVE;

        return ret;
    }
};


bool is_array_ref(const SV * const  a) {
    return (SvROK(a) && SvTYPE(SvRV(a)) == SVt_PVAV);
}


void AV_to_vector(AV * array, std::vector<SV*> &elements) {
    dTHX; 
    size_t len = av_len(array) + 1;
    
    DEBUG("array length", len);

    elements.reserve(len);

    SV *buf = &PL_sv_undef;
    for (size_t i=0; i<len; ++i) {
        buf = *(SV **)av_fetch(array, i, true);
        elements.push_back(buf);
    }
}


#line 91 "Statistic.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 143 "Statistic.c"

XS(XS_Algorithm__Statistic_kth_order_statistic); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__Statistic_kth_order_statistic)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "compare, array_ref, k");
    {
	SV *	RETVAL;
	SV*	compare = ST(0);
	SV *	array_ref = ST(1);
	SV *	k = ST(2);
#line 87 "Statistic.xs"
    {
        if (!is_array_ref(array_ref)) {
            warn("Not an array refference passed"); 
            XSRETURN_UNDEF;
        }

        AV * array = (AV*)SvRV(array_ref);
        std::vector<SV*> elements;

        AV_to_vector(array, elements);

        DEBUG_ITERABLE("elements", elements.begin(), elements.end());

        try {
            auto it = algo::KthOrderStatistic<std::vector<SV*>::iterator, PerlCompare>(
                elements.begin(), 
                elements.end(), 
                (size_t)SvUV(k),
                PerlCompare(compare)
            );

            DEBUG_ITERABLE("elements after", elements.begin(), elements.end());
            RETVAL = SvREFCNT_inc(*it);
        }
        catch (std::exception &e) {
            warn(e.what()); 
            XSRETURN_UNDEF;
        }
    }

#line 191 "Statistic.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Algorithm__Statistic_mediana); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__Statistic_mediana)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "compare, array_ref");
    {
	SV *	RETVAL;
	SV*	compare = ST(0);
	SV *	array_ref = ST(1);
#line 124 "Statistic.xs"
    {
        if (!is_array_ref(array_ref)) {
            warn("Not an array refference passed"); 
            XSRETURN_UNDEF;
        }

        AV * array = (AV*)SvRV(array_ref);
        std::vector<SV*> elements;

        AV_to_vector(array, elements);

        size_t k = elements.size() / 2;

        try {
            auto it = algo::KthOrderStatistic<std::vector<SV*>::iterator, PerlCompare>(
                elements.begin(), 
                elements.end(), 
                k,
                PerlCompare(compare)
            );

            DEBUG_ITERABLE("elements after", elements.begin(), elements.end());
            RETVAL = SvREFCNT_inc(*it);
        }
        catch (std::exception &e) {
            warn(e.what()); 
            XSRETURN_UNDEF;
        }
    }

#line 244 "Statistic.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Algorithm__Statistic); /* prototype to pass -Wmissing-prototypes */
XS(boot_Algorithm__Statistic)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        (void)newXSproto_portable("Algorithm::Statistic::kth_order_statistic", XS_Algorithm__Statistic_kth_order_statistic, file, "&$$");
        (void)newXSproto_portable("Algorithm::Statistic::mediana", XS_Algorithm__Statistic_mediana, file, "&$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

